# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of application replicas
replicaCount: 2

# Container image
image:
  repository: ghcr.io/zain5424/devops-frontend
  pullPolicy: Always
  tag: "latest"

# Secrets for pulling an image from a private repository
imagePullSecrets: []

# Override chart name
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Kubernetes service configuration
service:
  type: LoadBalancer
  port: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Gateway API HTTPRoute
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

# Resource requests and limits
resources: {}

# Liveness probe
livenessProbe:
  httpGet:
    path: /
    port: http

# Readiness probe
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes
volumes: []

# Additional volume mounts
volumeMounts: []

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}